name: Shallow Clone Example
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          sparse-checkout: true

      - name: Sparse checkout config
        run: |
          git config core.sparseCheckout true
          echo "admin/*" >> .git/info/sparse-checkout
          echo "Archive/*" >> .git/info/sparse-checkout
          echo "Art/*" >> .git/info/sparse-checkout
          echo "School/*" >> .git/info/sparse-checkout
          echo "The-Aviary/*" >> .git/info/sparse-checkout
          echo "Idiot!/index_files/fp_32.0.0.371_archive/Source/*" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/cactus/34/_cactus-34.7z" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/cactus/69/_cactus-69.7z.001" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/cactus/69/_cactus-69.7z.002" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/cactus/420/_cactus-420.7z.001" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/cactus/420/_cactus-420.7z.002" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/cactus/420/_cactus-420.7z.003" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/cactus/420/_cactus-420.7z.004" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/cactus/420/_cactus-420.7z.005" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/cactus/420/_cactus-420.7z.006" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/cactus/420/_cactus-420.7z.007" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/cactus/420/_cactus-420.7z.008" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/cactus/420/_cactus-420.7z.008" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/cactus/1337/_cactus-1337.7z.001" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/cactus/1337/_cactus-1337.7z.002" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/cactus/1337/_cactus-1337.7z.003" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/cactus/1337/_cactus-1337.7z.004" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/cactus/1337/_cactus-1337.7z.005" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/cactus/1337/_cactus-1337.7z.006" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/cactus/1337/_cactus-1337.7z.007" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/cactus/1337/_cactus-1337.7z.008" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/cactus/1337/_cactus-1337.7z.009" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/cactus/1337/_cactus-1337.7z.010" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/cactus/1337/_cactus-1337.7z.011" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/cactus/1337/_cactus-1337.7z.012" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/cactus/1337/_cactus-1337.7z.013" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/cactus/1337/_cactus-1337.7z.014" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/cactus/1337/_cactus-1337.7z.015" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/cactus/1337/_cactus-1337.7z.016" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/cactus/1337/_cactus-1337.7z.017" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/cactus/1337/_cactus-1337.7z.018" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/cactus/1337/_cactus-1337.7z.019" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/cactus/1337/_cactus-1337.7z.020" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/cactus/1337/_cactus-1337.7z.021" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/cactus/1337/_cactus-1337.7z.022" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/cactus/1337/_cactus-1337.7z.023" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/palm/34/_palm-34.7z.001" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/palm/34/_palm-34.7z.002" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/palm/69/_palm-69.7z.001" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/palm/69/_palm-69.7z.002" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/palm/69/_palm-69.7z.003" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/palm/420/_palm-420.7z.001" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/palm/420/_palm-420.7z.002" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/palm/420/_palm-420.7z.003" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/palm/420/_palm-420.7z.004" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/palm/420/_palm-420.7z.005" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/palm/420/_palm-420.7z.006" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/palm/420/_palm-420.7z.007" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/palm/420/_palm-420.7z.008" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/palm/420/_palm-420.7z.009" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/palm/420/_palm-420.7z.010" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/palm/420/_palm-420.7z.011" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/palm/1337/_palm-1337.7z.001" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/palm/1337/_palm-1337.7z.002" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/palm/1337/_palm-1337.7z.003" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/palm/1337/_palm-1337.7z.004" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/palm/1337/_palm-1337.7z.005" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/palm/1337/_palm-1337.7z.006" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/palm/1337/_palm-1337.7z.007" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/palm/1337/_palm-1337.7z.008" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/palm/1337/_palm-1337.7z.009" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/palm/1337/_palm-1337.7z.010" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/palm/1337/_palm-1337.7z.011" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/palm/1337/_palm-1337.7z.012" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/palm/1337/_palm-1337.7z.013" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/palm/1337/_palm-1337.7z.014" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/palm/1337/_palm-1337.7z.015" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/palm/1337/_palm-1337.7z.016" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/palm/1337/_palm-1337.7z.017" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/palm/1337/_palm-1337.7z.018" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/palm/1337/_palm-1337.7z.019" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/palm/1337/_palm-1337.7z.020" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/palm/1337/_palm-1337.7z.021" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/palm/1337/_palm-1337.7z.022" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/palm/1337/_palm-1337.7z.023" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/palm/1337/_palm-1337.7z.024" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/palm/1337/_palm-1337.7z.025" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/palm/1337/_palm-1337.7z.026" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/palm/1337/_palm-1337.7z.027" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/palm/1337/_palm-1337.7z.028" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/palm/1337/_palm-1337.7z.029" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/palm/1337/_palm-1337.7z.030" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/palm/1337/_palm-1337.7z.031" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/palm/1337/_palm-1337.7z.032" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/pine/34/_pine-34.7z.001" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/pine/34/_pine-34.7z.002" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/pine/69/_pine-69.7z.001" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/pine/69/_pine-69.7z.002" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/pine/420/_pine-420.7z.001" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/pine/420/_pine-420.7z.002" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/pine/420/_pine-420.7z.003" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/pine/420/_pine-420.7z.004" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/pine/420/_pine-420.7z.005" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/pine/420/_pine-420.7z.006" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/pine/420/_pine-420.7z.007" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/pine/420/_pine-420.7z.008" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/pine/420/_pine-420.7z.009" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/pine/1337/_pine-1337.7z.001" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/pine/1337/_pine-1337.7z.002" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/pine/1337/_pine-1337.7z.003" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/pine/1337/_pine-1337.7z.004" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/pine/1337/_pine-1337.7z.005" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/pine/1337/_pine-1337.7z.006" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/pine/1337/_pine-1337.7z.007" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/pine/1337/_pine-1337.7z.008" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/pine/1337/_pine-1337.7z.009" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/pine/1337/_pine-1337.7z.010" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/pine/1337/_pine-1337.7z.011" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/pine/1337/_pine-1337.7z.012" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/pine/1337/_pine-1337.7z.013" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/pine/1337/_pine-1337.7z.014" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/pine/1337/_pine-1337.7z.015" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/pine/1337/_pine-1337.7z.016" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/pine/1337/_pine-1337.7z.017" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/pine/1337/_pine-1337.7z.018" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/pine/1337/_pine-1337.7z.019" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/pine/1337/_pine-1337.7z.020" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/pine/1337/_pine-1337.7z.021" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/pine/1337/_pine-1337.7z.022" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/pine/1337/_pine-1337.7z.023" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/pine/1337/_pine-1337.7z.024" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/pine/1337/_pine-1337.7z.025" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/pine/1337/_pine-1337.7z.026" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/wheat/34/_wheat-34.7z" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/wheat/69/_wheat-69.7z" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/wheat/420/_wheat-420.7z.001" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/wheat/420/_wheat-420.7z.002" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/wheat/420/_wheat-420.7z.003" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/wheat/420/_wheat-420.7z.004" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/wheat/420/_wheat-420.7z.005" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/wheat/420/_wheat-420.7z.006" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/wheat/1337/_wheat-1337.7z.001" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/wheat/1337/_wheat-1337.7z.002" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/wheat/1337/_wheat-1337.7z.003" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/wheat/1337/_wheat-1337.7z.004" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/wheat/1337/_wheat-1337.7z.005" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/wheat/1337/_wheat-1337.7z.006" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/wheat/1337/_wheat-1337.7z.007" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/wheat/1337/_wheat-1337.7z.008" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/wheat/1337/_wheat-1337.7z.009" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/wheat/1337/_wheat-1337.7z.010" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/wheat/1337/_wheat-1337.7z.011" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/wheat/1337/_wheat-1337.7z.012" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/wheat/1337/_wheat-1337.7z.013" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/wheat/1337/_wheat-1337.7z.014" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/wheat/1337/_wheat-1337.7z.015" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/wheat/1337/_wheat-1337.7z.016" >> .git/info/sparse-checkout
          echo "Plant-generator/plant-zips/wheat/1337/_wheat-1337.7z.017" >> .git/info/sparse-checkout

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site