name: Shallow Clone Example
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          ref: ${{ github.ref }}  # Use the current branch or tag
          exclude: |
            admin/ 
            Archive/
            Art/
            School/
            The-Aviary/
            Idiot!/index_files/fp_32.0.0.371_archive/Source/
            Plant-generator/plant-zips/cactus/34/_cactus-34.7z
            Plant-generator/plant-zips/cactus/69/_cactus-69.7z.001
            Plant-generator/plant-zips/cactus/69/_cactus-69.7z.002
            Plant-generator/plant-zips/cactus/420/_cactus-420.7z.001
            Plant-generator/plant-zips/cactus/420/_cactus-420.7z.002
            Plant-generator/plant-zips/cactus/420/_cactus-420.7z.003
            Plant-generator/plant-zips/cactus/420/_cactus-420.7z.004
            Plant-generator/plant-zips/cactus/420/_cactus-420.7z.005
            Plant-generator/plant-zips/cactus/420/_cactus-420.7z.006
            Plant-generator/plant-zips/cactus/420/_cactus-420.7z.007
            Plant-generator/plant-zips/cactus/420/_cactus-420.7z.008
            Plant-generator/plant-zips/cactus/420/_cactus-420.7z.008
            Plant-generator/plant-zips/cactus/1337/_cactus-1337.7z.001
            Plant-generator/plant-zips/cactus/1337/_cactus-1337.7z.002
            Plant-generator/plant-zips/cactus/1337/_cactus-1337.7z.003
            Plant-generator/plant-zips/cactus/1337/_cactus-1337.7z.004
            Plant-generator/plant-zips/cactus/1337/_cactus-1337.7z.005
            Plant-generator/plant-zips/cactus/1337/_cactus-1337.7z.006
            Plant-generator/plant-zips/cactus/1337/_cactus-1337.7z.007
            Plant-generator/plant-zips/cactus/1337/_cactus-1337.7z.008
            Plant-generator/plant-zips/cactus/1337/_cactus-1337.7z.009
            Plant-generator/plant-zips/cactus/1337/_cactus-1337.7z.010
            Plant-generator/plant-zips/cactus/1337/_cactus-1337.7z.011
            Plant-generator/plant-zips/cactus/1337/_cactus-1337.7z.012
            Plant-generator/plant-zips/cactus/1337/_cactus-1337.7z.013
            Plant-generator/plant-zips/cactus/1337/_cactus-1337.7z.014
            Plant-generator/plant-zips/cactus/1337/_cactus-1337.7z.015
            Plant-generator/plant-zips/cactus/1337/_cactus-1337.7z.016
            Plant-generator/plant-zips/cactus/1337/_cactus-1337.7z.017
            Plant-generator/plant-zips/cactus/1337/_cactus-1337.7z.018
            Plant-generator/plant-zips/cactus/1337/_cactus-1337.7z.019
            Plant-generator/plant-zips/cactus/1337/_cactus-1337.7z.020
            Plant-generator/plant-zips/cactus/1337/_cactus-1337.7z.021
            Plant-generator/plant-zips/cactus/1337/_cactus-1337.7z.022
            Plant-generator/plant-zips/cactus/1337/_cactus-1337.7z.023
            Plant-generator/plant-zips/palm/34/_palm-34.7z.001
            Plant-generator/plant-zips/palm/34/_palm-34.7z.002
            Plant-generator/plant-zips/palm/69/_palm-69.7z.001
            Plant-generator/plant-zips/palm/69/_palm-69.7z.002
            Plant-generator/plant-zips/palm/69/_palm-69.7z.003
            Plant-generator/plant-zips/palm/420/_palm-420.7z.001
            Plant-generator/plant-zips/palm/420/_palm-420.7z.002
            Plant-generator/plant-zips/palm/420/_palm-420.7z.003
            Plant-generator/plant-zips/palm/420/_palm-420.7z.004
            Plant-generator/plant-zips/palm/420/_palm-420.7z.005
            Plant-generator/plant-zips/palm/420/_palm-420.7z.006
            Plant-generator/plant-zips/palm/420/_palm-420.7z.007
            Plant-generator/plant-zips/palm/420/_palm-420.7z.008
            Plant-generator/plant-zips/palm/420/_palm-420.7z.009
            Plant-generator/plant-zips/palm/420/_palm-420.7z.010
            Plant-generator/plant-zips/palm/420/_palm-420.7z.011
            Plant-generator/plant-zips/palm/1337/_palm-1337.7z.001
            Plant-generator/plant-zips/palm/1337/_palm-1337.7z.002
            Plant-generator/plant-zips/palm/1337/_palm-1337.7z.003
            Plant-generator/plant-zips/palm/1337/_palm-1337.7z.004
            Plant-generator/plant-zips/palm/1337/_palm-1337.7z.005
            Plant-generator/plant-zips/palm/1337/_palm-1337.7z.006
            Plant-generator/plant-zips/palm/1337/_palm-1337.7z.007
            Plant-generator/plant-zips/palm/1337/_palm-1337.7z.008
            Plant-generator/plant-zips/palm/1337/_palm-1337.7z.009
            Plant-generator/plant-zips/palm/1337/_palm-1337.7z.010
            Plant-generator/plant-zips/palm/1337/_palm-1337.7z.011
            Plant-generator/plant-zips/palm/1337/_palm-1337.7z.012
            Plant-generator/plant-zips/palm/1337/_palm-1337.7z.013
            Plant-generator/plant-zips/palm/1337/_palm-1337.7z.014
            Plant-generator/plant-zips/palm/1337/_palm-1337.7z.015
            Plant-generator/plant-zips/palm/1337/_palm-1337.7z.016
            Plant-generator/plant-zips/palm/1337/_palm-1337.7z.017
            Plant-generator/plant-zips/palm/1337/_palm-1337.7z.018
            Plant-generator/plant-zips/palm/1337/_palm-1337.7z.019
            Plant-generator/plant-zips/palm/1337/_palm-1337.7z.020
            Plant-generator/plant-zips/palm/1337/_palm-1337.7z.021
            Plant-generator/plant-zips/palm/1337/_palm-1337.7z.022
            Plant-generator/plant-zips/palm/1337/_palm-1337.7z.023
            Plant-generator/plant-zips/palm/1337/_palm-1337.7z.024
            Plant-generator/plant-zips/palm/1337/_palm-1337.7z.025
            Plant-generator/plant-zips/palm/1337/_palm-1337.7z.026
            Plant-generator/plant-zips/palm/1337/_palm-1337.7z.027
            Plant-generator/plant-zips/palm/1337/_palm-1337.7z.028
            Plant-generator/plant-zips/palm/1337/_palm-1337.7z.029
            Plant-generator/plant-zips/palm/1337/_palm-1337.7z.030
            Plant-generator/plant-zips/palm/1337/_palm-1337.7z.031
            Plant-generator/plant-zips/palm/1337/_palm-1337.7z.032
            Plant-generator/plant-zips/pine/34/_pine-34.7z.001
            Plant-generator/plant-zips/pine/34/_pine-34.7z.002
            Plant-generator/plant-zips/pine/69/_pine-69.7z.001
            Plant-generator/plant-zips/pine/69/_pine-69.7z.002
            Plant-generator/plant-zips/pine/420/_pine-420.7z.001
            Plant-generator/plant-zips/pine/420/_pine-420.7z.002
            Plant-generator/plant-zips/pine/420/_pine-420.7z.003
            Plant-generator/plant-zips/pine/420/_pine-420.7z.004
            Plant-generator/plant-zips/pine/420/_pine-420.7z.005
            Plant-generator/plant-zips/pine/420/_pine-420.7z.006
            Plant-generator/plant-zips/pine/420/_pine-420.7z.007
            Plant-generator/plant-zips/pine/420/_pine-420.7z.008
            Plant-generator/plant-zips/pine/420/_pine-420.7z.009
            Plant-generator/plant-zips/pine/1337/_pine-1337.7z.001
            Plant-generator/plant-zips/pine/1337/_pine-1337.7z.002
            Plant-generator/plant-zips/pine/1337/_pine-1337.7z.003
            Plant-generator/plant-zips/pine/1337/_pine-1337.7z.004
            Plant-generator/plant-zips/pine/1337/_pine-1337.7z.005
            Plant-generator/plant-zips/pine/1337/_pine-1337.7z.006
            Plant-generator/plant-zips/pine/1337/_pine-1337.7z.007
            Plant-generator/plant-zips/pine/1337/_pine-1337.7z.008
            Plant-generator/plant-zips/pine/1337/_pine-1337.7z.009
            Plant-generator/plant-zips/pine/1337/_pine-1337.7z.010
            Plant-generator/plant-zips/pine/1337/_pine-1337.7z.011
            Plant-generator/plant-zips/pine/1337/_pine-1337.7z.012
            Plant-generator/plant-zips/pine/1337/_pine-1337.7z.013
            Plant-generator/plant-zips/pine/1337/_pine-1337.7z.014
            Plant-generator/plant-zips/pine/1337/_pine-1337.7z.015
            Plant-generator/plant-zips/pine/1337/_pine-1337.7z.016
            Plant-generator/plant-zips/pine/1337/_pine-1337.7z.017
            Plant-generator/plant-zips/pine/1337/_pine-1337.7z.018
            Plant-generator/plant-zips/pine/1337/_pine-1337.7z.019
            Plant-generator/plant-zips/pine/1337/_pine-1337.7z.020
            Plant-generator/plant-zips/pine/1337/_pine-1337.7z.021
            Plant-generator/plant-zips/pine/1337/_pine-1337.7z.022
            Plant-generator/plant-zips/pine/1337/_pine-1337.7z.023
            Plant-generator/plant-zips/pine/1337/_pine-1337.7z.024
            Plant-generator/plant-zips/pine/1337/_pine-1337.7z.025
            Plant-generator/plant-zips/pine/1337/_pine-1337.7z.026
            Plant-generator/plant-zips/wheat/34/_wheat-34.7z
            Plant-generator/plant-zips/wheat/69/_wheat-69.7z
            Plant-generator/plant-zips/wheat/420/_wheat-420.7z.001
            Plant-generator/plant-zips/wheat/420/_wheat-420.7z.002
            Plant-generator/plant-zips/wheat/420/_wheat-420.7z.003
            Plant-generator/plant-zips/wheat/420/_wheat-420.7z.004
            Plant-generator/plant-zips/wheat/420/_wheat-420.7z.005
            Plant-generator/plant-zips/wheat/420/_wheat-420.7z.006
            Plant-generator/plant-zips/wheat/1337/_wheat-1337.7z.001
            Plant-generator/plant-zips/wheat/1337/_wheat-1337.7z.002
            Plant-generator/plant-zips/wheat/1337/_wheat-1337.7z.003
            Plant-generator/plant-zips/wheat/1337/_wheat-1337.7z.004
            Plant-generator/plant-zips/wheat/1337/_wheat-1337.7z.005
            Plant-generator/plant-zips/wheat/1337/_wheat-1337.7z.006
            Plant-generator/plant-zips/wheat/1337/_wheat-1337.7z.007
            Plant-generator/plant-zips/wheat/1337/_wheat-1337.7z.008
            Plant-generator/plant-zips/wheat/1337/_wheat-1337.7z.009
            Plant-generator/plant-zips/wheat/1337/_wheat-1337.7z.010
            Plant-generator/plant-zips/wheat/1337/_wheat-1337.7z.011
            Plant-generator/plant-zips/wheat/1337/_wheat-1337.7z.012
            Plant-generator/plant-zips/wheat/1337/_wheat-1337.7z.013
            Plant-generator/plant-zips/wheat/1337/_wheat-1337.7z.014
            Plant-generator/plant-zips/wheat/1337/_wheat-1337.7z.015
            Plant-generator/plant-zips/wheat/1337/_wheat-1337.7z.016
            Plant-generator/plant-zips/wheat/1337/_wheat-1337.7z.017
